# Generated by Django 5.2.17 on 2026-10-06 12:04

import django.db.models.deletion
import django.db.models.expressions
import pgvector.django.vector
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunSQL(
            sql="CREATE EXTENSION IF NOT EXISTS vector;",
            reverse_sql=migrations.RunSQL.noop,
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.topic')),
                ('title', models.TextField()),
                ('type', models.TextField()),
                ('release_mode', models.TextField(db_default='review')),
                ('due_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'assignments',
            },
        ),
        migrations.CreateModel(
            name='AssignmentQuestion',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessment.assignment')),
                ('position', models.IntegerField(db_default=0)),
                ('question', models.TextField()),
                ('options', models.JSONField(null=True)),
                ('answer_key', models.TextField(null=True)),
            ],
            options={
                'db_table': 'assignment_questions',
            },
        ),
        migrations.CreateModel(
            name='RubricCriterion',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='assessment.assignment')),
                ('position', models.IntegerField(db_default=0)),
                ('name', models.TextField()),
                ('weight', models.IntegerField()),
                ('level_1', models.TextField(db_default='')),
                ('level_2', models.TextField(db_default='')),
                ('level_3', models.TextField(db_default='')),
                ('level_4', models.TextField(db_default='')),
                ('prompt_notes', models.TextField(db_default='')),
            ],
            options={
                'db_table': 'rubric_criteria',
            },
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assignment', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessment.assignment')),
                ('student', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to=settings.AUTH_USER_MODEL)),
                ('answer_text', models.TextField(null=True)),
                ('answers', models.JSONField(db_default=django.db.models.expressions.RawSQL("'[]'::jsonb", []), default=list)),
                ('file_name', models.TextField(null=True)),
                ('extracted_text', models.TextField(null=True)),
                ('extraction_ok', models.BooleanField(null=True)),
                ('status', models.TextField(db_default='draft')),
                ('submitted_at', models.DateTimeField(null=True)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'submissions',
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission', models.OneToOneField(db_constraint=False, on_delete=django.db.models.deletion.CASCADE, related_name='grade', to='assessment.submission')),
                ('state', models.TextField(db_default='draft')),
                ('criteria', models.JSONField(db_default=django.db.models.expressions.RawSQL("'[]'::jsonb", []), default=list)),
                ('feedback', models.TextField(db_default='')),
                ('summary', models.TextField(db_default='')),
                ('nilai', models.DecimalField(db_default=Decimal('0'), decimal_places=2, max_digits=5)),
                ('predikat', models.TextField(db_default='D')),
                ('source', models.TextField()),
                ('created_by', models.ForeignKey(db_column='created_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(db_column='updated_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('published_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
                ('updated_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'grades',
            },
        ),
        migrations.CreateModel(
            name='GradeRevision',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('grade', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='revisions', to='assessment.grade')),
                ('snapshot', models.JSONField()),
                ('nilai', models.DecimalField(decimal_places=2, max_digits=5)),
                ('predikat', models.TextField()),
                ('state', models.TextField()),
                ('changed_by', models.ForeignKey(db_column='changed_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('changed_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'grade_revisions',
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='assessment.submission')),
                ('position', models.IntegerField()),
                ('content', models.TextField()),
                ('embedding', pgvector.django.vector.VectorField(dimensions=3072, null=True)),
            ],
            options={
                'db_table': 'document_chunks',
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ('essay', 'pg', 'pdf', 'docx'))), name='assignments_type_check'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(('release_mode__in', ('review', 'langsung'))), name='assignments_release_mode_check'),
        ),
        migrations.AddConstraint(
            model_name='assignmentquestion',
            constraint=models.UniqueConstraint(fields=('assignment', 'position'), name='assignment_questions_assignment_id_position_key'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.UniqueConstraint(fields=('assignment', 'student'), name='submissions_assignment_id_student_id_key'),
        ),
        migrations.AddConstraint(
            model_name='submission',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ('draft', 'submitted', 'needs_review'))), name='submissions_status_check'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('state__in', ('draft', 'published'))), name='grades_state_check'),
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('model', 'manual', 'empty', 'code'))), name='grades_source_check'),
        ),
        # 31-char index name exceeds Django's 30-char limit; matches original DDL.
        migrations.RunSQL(
            sql="CREATE INDEX IF NOT EXISTS document_chunks_submission_idx ON document_chunks (submission_id);",
            reverse_sql=migrations.RunSQL.noop,
        ),
        # FK constraints with the original schema.ts names and ON DELETE
        # actions (models use db_constraint=False so Django emits none).
        migrations.RunSQL(
            sql=[
                "ALTER TABLE ONLY public.assignment_questions ADD CONSTRAINT assignment_questions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.assignments ADD CONSTRAINT assignments_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.document_chunks ADD CONSTRAINT document_chunks_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.grade_revisions ADD CONSTRAINT grade_revisions_changed_by_fkey FOREIGN KEY (changed_by) REFERENCES public.users(id);",
                "ALTER TABLE ONLY public.grade_revisions ADD CONSTRAINT grade_revisions_grade_id_fkey FOREIGN KEY (grade_id) REFERENCES public.grades(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.grades ADD CONSTRAINT grades_created_by_fkey FOREIGN KEY (created_by) REFERENCES public.users(id);",
                "ALTER TABLE ONLY public.grades ADD CONSTRAINT grades_submission_id_fkey FOREIGN KEY (submission_id) REFERENCES public.submissions(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.grades ADD CONSTRAINT grades_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);",
                "ALTER TABLE ONLY public.rubric_criteria ADD CONSTRAINT rubric_criteria_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.submissions ADD CONSTRAINT submissions_assignment_id_fkey FOREIGN KEY (assignment_id) REFERENCES public.assignments(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.submissions ADD CONSTRAINT submissions_student_id_fkey FOREIGN KEY (student_id) REFERENCES public.users(id) ON DELETE CASCADE;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
