# Generated by Django 5.2.17 on 2026-10-06 12:04

import django.db.models.deletion
import django.db.models.expressions
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('email', models.TextField()),
                ('password', models.TextField(db_column='password_hash', null=True)),
                ('role', models.TextField()),
                ('status', models.TextField(db_default='active')),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'users',
                'constraints': [models.UniqueConstraint(fields=('email',), name='users_email_key'), models.CheckConstraint(condition=models.Q(('role__in', ('admin', 'lecturer', 'student'))), name='users_role_check'), models.CheckConstraint(condition=models.Q(('status__in', ('active', 'inactive'))), name='users_status_check')],
            },
        ),
        migrations.CreateModel(
            name='AppSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('app_name', models.TextField(db_default='MiniCourse')),
                ('footer_text', models.TextField(db_default='')),
                ('logo', models.BinaryField(null=True)),
                ('logo_type', models.TextField(null=True)),
                ('logo_version', models.IntegerField(db_default=0)),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'app_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='app_settings_id_check')],
            },
        ),
        migrations.CreateModel(
            name='ModelSettings',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('provider_label', models.TextField(db_default='')),
                ('base_url', models.TextField(db_default='')),
                ('api_key', models.TextField(db_default='')),
                ('model_name', models.TextField(db_default='')),
                ('temperature', models.DecimalField(db_default=Decimal('0.20'), decimal_places=2, max_digits=3)),
                ('max_tokens', models.IntegerField(db_default=1200)),
                ('system_preamble', models.TextField(db_default='')),
                ('emb_base_url', models.TextField(db_default='')),
                ('emb_api_key', models.TextField(db_default='')),
                ('emb_model_name', models.TextField(db_default='')),
                ('updated_at', models.DateTimeField(null=True)),
                ('updated_by', models.ForeignKey(db_column='updated_by', db_constraint=False, db_index=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'model_settings',
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='model_settings_id_check')],
            },
        ),
        # FK constraints with the original schema.ts names (models use
        # db_constraint=False so Django does not generate hashed names).
        migrations.RunSQL(
            sql=[
                "ALTER TABLE ONLY public.app_settings ADD CONSTRAINT app_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);",
                "ALTER TABLE ONLY public.model_settings ADD CONSTRAINT model_settings_updated_by_fkey FOREIGN KEY (updated_by) REFERENCES public.users(id);",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
