# Generated by Django 5.2.17 on 2026-10-06 12:04

import django.db.models.deletion
import django.db.models.expressions
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Period',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('is_active', models.BooleanField(db_default=False)),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'periods',
                'constraints': [models.UniqueConstraint(fields=('name',), name='periods_name_key')],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.TextField()),
                ('name', models.TextField()),
                ('semester', models.IntegerField()),
                ('sks', models.IntegerField()),
                ('period', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='courses', to='academics.period')),
                ('section', models.TextField(db_default='A')),
                ('archived_at', models.DateTimeField(null=True)),
            ],
            options={
                'db_table': 'courses',
            },
        ),
        migrations.CreateModel(
            name='CourseLecturer',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='lecturers', serialize=False, to='academics.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user')),
            ],
            options={
                'db_table': 'course_lecturers',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='enrolled', serialize=False, to='academics.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='accounts.user')),
                ('created_at', models.DateTimeField(db_default=django.db.models.expressions.RawSQL('now()', []), editable=False)),
            ],
            options={
                'db_table': 'enrollments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='academics.course')),
                ('week', models.IntegerField()),
                ('title', models.TextField()),
            ],
            options={
                'db_table': 'topics',
            },
        ),
        migrations.CreateModel(
            name='MateriBlock',
            fields=[
                ('id', models.UUIDField(db_default=django.db.models.expressions.RawSQL('gen_random_uuid()', []), default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.ForeignKey(db_constraint=False, db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='blocks', to='academics.topic')),
                ('type', models.TextField()),
                ('body', models.TextField(null=True)),
                ('url', models.TextField(null=True)),
                ('file_name', models.TextField(null=True)),
                ('position', models.IntegerField(db_default=0)),
            ],
            options={
                'db_table': 'materi_blocks',
            },
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.UniqueConstraint(fields=('code', 'period', 'section'), name='courses_code_period_section_key'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(fields=('course', 'week'), name='topics_course_id_week_key'),
        ),
        migrations.AddConstraint(
            model_name='materiblock',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', ('richtext', 'link', 'file'))), name='materi_blocks_type_check'),
        ),
        # Exact original DDL (db_constraint=False on the models): composite-PK
        # join tables have no Django equivalent, and all FKs here are created
        # with the original names and ON DELETE actions from schema.ts.
        migrations.RunSQL(
            sql=[
                """
                CREATE TABLE IF NOT EXISTS course_lecturers (
                  course_id uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
                  user_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  PRIMARY KEY (course_id, user_id)
                );
                """,
                """
                CREATE TABLE IF NOT EXISTS enrollments (
                  course_id uuid NOT NULL REFERENCES courses(id) ON DELETE CASCADE,
                  student_id uuid NOT NULL REFERENCES users(id) ON DELETE CASCADE,
                  created_at timestamptz NOT NULL DEFAULT now(),
                  PRIMARY KEY (course_id, student_id)
                );
                """,
                "ALTER TABLE ONLY public.courses ADD CONSTRAINT courses_period_id_fkey FOREIGN KEY (period_id) REFERENCES public.periods(id);",
                "ALTER TABLE ONLY public.topics ADD CONSTRAINT topics_course_id_fkey FOREIGN KEY (course_id) REFERENCES public.courses(id) ON DELETE CASCADE;",
                "ALTER TABLE ONLY public.materi_blocks ADD CONSTRAINT materi_blocks_topic_id_fkey FOREIGN KEY (topic_id) REFERENCES public.topics(id) ON DELETE CASCADE;",
            ],
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
